#! /usr/bin/env bash
#
# Run a one-off nats-server invocation for btests. By default, stores
# the server's PID file in the parent directory.
set -ux

nats-server --version >&2

NATS_ADDR=${NATS_ADDR:-127.0.0.1}
NATS_PID_FILE=${NATS_PID_FILE:-../nats.pid}

if [ -z "${NATS_PORT}" ]; then
    echo "No NATS_PORT environment variable set" >&2
    exit 1
fi

nats-server -a "${NATS_ADDR}" -p "${NATS_PORT%/tcp}" -P "${NATS_PID_FILE}"

exit 0
